# Generated by Django 5.0.7 on 2025-07-27 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='National ID must be 5-20 alphanumeric characters', regex='^[A-Za-z0-9]{5,20}$')], verbose_name='National ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Passport Number')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Guest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking', verbose_name='Booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['national_id'], name='guests_gues_nationa_ba8d66_idx'), models.Index(fields=['booking', 'is_primary'], name='guests_gues_booking_1e4d63_idx'), models.Index(fields=['phone'], name='guests_gues_phone_6b6426_idx'), models.Index(fields=['email'], name='guests_gues_email_e4fe59_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('booking',), name='unique_primary_guest_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(fields=('national_id', 'booking'), name='unique_guest_per_booking'),
        ),
    ]
