# Generated by Django 5.0.7 on 2025-07-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_is_trash'),
        ('guests', '0002_guest_booking_guest_is_primary_alter_guest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking', verbose_name='Booking'),
        ),
    ]
