# Generated by Django 5.0.7 on 2025-07-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_assigned_staff'),
        ('guests', '0003_alter_guest_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking', verbose_name='Booking'),
        ),
    ]
