# Generated by Django 4.2.10 on 2025-08-01 16:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('bookings', '0003_booking_booking_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start', models.DateField(verbose_name='شروع سال مالی')),
                ('default_currency', models.CharField(default='IRR', max_length=10, verbose_name='ارز پیش\u200cفرض')),
                ('auto_generate_daily_reports', models.BooleanField(default=True, verbose_name='تولید خودکار گزارش روزانه')),
                ('require_transaction_approval', models.BooleanField(default=False, verbose_name='نیاز به تایید تراکنش')),
                ('default_gateway_config', models.JSONField(blank=True, null=True, verbose_name='تنظیمات پیش\u200cفرض درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات حسابداری',
                'verbose_name_plural': 'تنظیمات حسابداری',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع حساب')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب/کارت')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('category', models.CharField(choices=[('bank_card', 'کارت بانکی'), ('cash', 'نقدی'), ('online_gateway', 'درگاه آنلاین'), ('pos', 'دستگاه کارت\u200cخوان'), ('bank_transfer', 'حواله بانکی'), ('check', 'چک'), ('other', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('gateway_config', models.JSONField(blank=True, null=True, verbose_name='تنظیمات درگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'انواع حساب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='شرح تراکنش')),
                ('transaction_date', models.DateTimeField(verbose_name='تاریخ تراکنش')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع خارجی')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش درگاه')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشتی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='برگشت خورده')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='دلیل برگشت')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برگشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accounttype', verbose_name='نوع حساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='رزرو')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guests.guest', verbose_name='مهمان')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='برگشت داده شده توسط')),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction', verbose_name='تراکنش برگشتی')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنشات',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع تراکنش')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد')),
                ('nature', models.CharField(choices=[('income', 'درآمد'), ('expense', 'مخارج'), ('transfer', 'انتقال')], max_length=10, verbose_name='ماهیت تراکنش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('default_account_debit', models.CharField(blank=True, max_length=20, verbose_name='حساب بدهکار پیش\u200cفرض')),
                ('default_account_credit', models.CharField(blank=True, max_length=20, verbose_name='حساب بستانکار پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype', verbose_name='نوع والد')),
            ],
            options={
                'verbose_name': 'نوع تراکنش',
                'verbose_name_plural': 'انواع تراکنش',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transaction_attachments/', verbose_name='فایل')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع فایل')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.transaction', verbose_name='تراکنش')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'پیوست تراکنش',
                'verbose_name_plural': 'پیوست\u200cهای تراکنش',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.transactiontype', verbose_name='نوع تراکنش'),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='کل درآمد')),
                ('cash_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='درآمد نقدی')),
                ('card_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='درآمد کارتی')),
                ('online_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='درآمد آنلاین')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='کل مخارج')),
                ('cash_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مخارج نقدی')),
                ('card_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مخارج کارتی')),
                ('income_transactions_count', models.IntegerField(default=0, verbose_name='تعداد تراکنشات درآمدی')),
                ('expense_transactions_count', models.IntegerField(default=0, verbose_name='تعداد تراکنشات مخارج')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نهایی شدن')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نهایی شده توسط')),
            ],
            options={
                'verbose_name': 'گزارش روزانه',
                'verbose_name_plural': 'گزارش\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='accounting__transac_0accd6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['booking'], name='accounting__booking_de8135_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['guest'], name='accounting__guest_i_38906d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='accounting__status_d96d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='accounting__transac_fcce9c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_type'], name='accounting__account_08fb4f_idx'),
        ),
    ]
