# Generated by Django 5.0.7 on 2025-07-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
    ]
