# Generated by Django 5.0.7 on 2025-07-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='default_amenities',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity', verbose_name='Default Amenities'),
        ),
    ]
