# Generated by Django 5.0.7 on 2025-07-27 08:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(db_index=True, verbose_name='Check In Date')),
                ('check_out', models.DateField(db_index=True, verbose_name='Check Out Date')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='reserved', max_length=20, verbose_name='Status')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Number of Children')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('room_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Room Rate per Night')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Advance Payment')),
                ('booking_source', models.CharField(choices=[('direct', 'Direct'), ('phone', 'Phone'), ('email', 'Email'), ('website', 'Website'), ('walk_in', 'Walk-in'), ('agent', 'Travel Agent'), ('online', 'Online Platform')], default='direct', max_length=50, verbose_name='Booking Source')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Actual Check-in Time')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Actual Check-out Time')),
                ('early_check_in', models.BooleanField(default=False, verbose_name='Early Check-in')),
                ('late_check_out', models.BooleanField(default=False, verbose_name='Late Check-out')),
                ('is_trash', models.BooleanField(db_index=True, default=False, verbose_name='Moved to Trash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
