# Generated by Django 5.0.7 on 2025-07-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0003_roomtype_default_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check In Date')),
                ('check_out', models.DateField(verbose_name='Check Out Date')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Children')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='reserved', max_length=20, verbose_name='Status')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest', verbose_name='Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'checked_in'])), fields=('room', 'check_in', 'check_out'), name='unique_booking_per_room_dates'),
        ),
    ]
