# Generated by Django 5.0.7 on 2025-07-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
    ]
