# Generated by Django 5.0.7 on 2025-07-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_bookings', to='guests.guest', verbose_name='Primary Guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_bo_check_i_3b9851_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'is_trash'], name='bookings_bo_status_027240_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'status'], name='bookings_bo_room_id_97310a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['primary_guest'], name='bookings_bo_primary_29544a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trash', False), ('status__in', ['reserved', 'confirmed', 'checked_in'])), fields=('room', 'check_in', 'check_out'), name='unique_booking_per_room_dates_v2'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_in__lt', models.F('check_out'))), name='check_in_before_check_out_v2'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('adults__gte', 1)), name='minimum_one_adult'),
        ),
    ]
