# Generated by Django 5.0.7 on 2025-07-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_adults_remove_booking_children_and_more'),
        ('guests', '0002_guest_booking_guest_is_primary_alter_guest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_bookings', to='guests.guest'),
        ),
    ]
