# Generated by Django 5.0.7 on 2025-07-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_primary_guest'),
        ('guests', '0002_guest_booking_guest_is_primary_alter_guest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='primary_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_bookings', to='guests.guest'),
        ),
    ]
