# Generated by Django 5.0.7 on 2025-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_primary_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
