# Generated by Django 5.0.7 on 2025-07-23 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_assigned_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='assigned_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
